AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

    FunctionName:
        Type: AWS::Serverless::Function
        Properties:
           Handler: index.handler
           Runtime: java8
           CodeUri: s3://bucketName/codepackage.zip
